-- 030. 문자형으로 데이터 유형 변환하기

-- 입사일을 분리, 월급 천 단위로 출력
SELECT ENAME, HIREDATE, 
TO_CHAR(HIREDATE,'YYYY') AS 연도,
TO_CHAR(HIREDATE,'MM') AS 월,
TO_CHAR(HIREDATE,'DD') AS 일,
TO_CHAR(HIREDATE,'DAY') AS 요일,
TO_CHAR(SAL, '9,999,999') AS 월급
FROM EMP;

-- 입사일 분리2 EXTRACT
SELECT ENAME, 
EXTRACT(YEAR FROM HIREDATE) AS 연도,
EXTRACT(MONTH FROM HIREDATE) AS 월,
EXTRACT(DAY FROM HIREDATE) AS 일
FROM EMP;

-- 월급 단위2 
-- L을 붙이면 통화 형태로 출력 가능
SELECT ENAME, SAL,
TO_CHAR(SAL, 'L999,999') AS 월급
FROM EMP;

-- WHERE절 활용 입사년도가 1981년인 사원
SELECT ENAME, HIREDATE
FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYY') = '1981';