-- 031. 날짜형으로 데이터 유형 변환하기

-- 현재 SESSION의 날짜 형식 확인
SELECT *
FROM NLS_SESSION_PARAMETERS
WHERE PARAMETER = 'NLS_DATE_FORMAT';

-- 현재 SESSION의 날짜 형식 변경
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';

-- 1981년 11월 17일 입사자
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE = TO_DATE('81/11/17','RR/MM/DD');