-- 042. 데이터 분석 함수로 순위 출력하기2
-- RANK: 동일 순위가 있을 경우 다음 순위는 COUNT(동일 순위) + 1
-- DENSE_RANK: 동일 순위가 있을 경우 다음 순위는 동일 순위 + 1

-- 연봉 순위
SELECT ENAME, JOB, SAL, DENSE_RANK() OVER (ORDER BY SAL DESC) AS 순위
FROM EMP
WHERE JOB IN ('ANALYST', 'MANAGER');

-- 직업별 연봉 순위
SELECT ENAME, SAL, JOB, DENSE_RANK() OVER (PARTITION BY JOB ORDER BY SAL DESC) AS 순위
FROM EMP
WHERE JOB IN ('ANALYST', 'MANAGER');

-- 값 추가 시 해당 값 순위 확인
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';
SELECT DENSE_RANK('81/11/17') WITHIN GROUP (ORDER BY HIREDATE ASC) 순위
FROM EMP;
