-- 050. 데이터 분석 함수로 누적 데이터 출력하기

-- SUM() OVER (ORDER BY COL ROWS BETWENN UNBOUNDED PRECEDING AND CURRENT ROW): 누계
-- UNBOUNDED PRECEDING: 첫 번째 행
-- UNBOUNDED FOLLOWING: 마지막 행
-- CURRENT ROW: 현재 행
SELECT EMPNO, ENAME, SAL,
SUM(SAL) OVER (ORDER BY ENAME ROWS
               BETWEEN UNBOUNDED PRECEDING
               AND CURRENT ROW) AS 누적합계,
SUM(SAL) OVER (ORDER BY ENAME ROWS
               BETWEEN UNBOUNDED PRECEDING
               AND UNBOUNDED FOLLOWING) AS "전체합계로 출력"
FROM EMP
WHERE JOB IN ('ANALYST', 'MANAGER');