-- 054. 데이터 분석 함수로 집계 결과 출력하기3
-- GROUPING SETS: 집계하고 싶은 컬럼을 직접 지정해서 출력
SELECT DEPTNO, JOB, SUM(SAL) AS 합계
FROM EMP
GROUP BY GROUPING SETS( (DEPTNO), (JOB), () )
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, SUM(SAL) AS 합계
FROM EMP
GROUP BY GROUPING SETS( (DEPTNO, JOB), () )
ORDER BY DEPTNO, JOB;