-- 055. 데이터 분석 함수로 출력 결과 넘버링 하기
SELECT ENAME, SAL, ROW_NUMBER() OVER (ORDER BY ENAME) AS OBS_NUMBER
FROM EMP;

-- 부서번호별 이름별로 넘버링
SELECT DEPTNO, ENAME, ROW_NUMBER() OVER (PARTITION BY DEPTNO ORDER BY ENAME) AS OBS_NUMBER
FROM EMP;