-- 082. 데이터 입력, 수정, 삭제 한번에 하기

-- 작업 전 수행 LOC 추가
ALTER TABLE EMP
ADD LOC VARCHAR2(10);


-- LOC 값이 DEPT에 있으면 업데이트, 없으면 추가
-- MERGE INTO 변경테이블
-- USING 소스테이블
MERGE INTO EMP A
USING DEPT B ON (A.DEPTNO = B.DEPTNO)
-- MERGE UPDATE 구문
WHEN MATCHED THEN
UPDATE SET A.LOC = B.LOC
-- MERGE INSERT 구문
WHEN NOT MATCHED THEN
INSERT (A.EMPNO, A.DEPTNO, A.LOC) VALUES (1111, B.DEPTNO, B.LOC);