-- 091. 계층형 질의문으로 서열을 주고 데이터 출력하기3

-- ORDER SIBLINGS BY: 서열은 유지 하면서 정렬하기 
SELECT RPAD('-', LEVEL*2, '-') || ENAME AS EMPLOYEE, LEVEL, SAL, JOB
FROM EMP
START WITH ENAME = 'KING'
CONNECT BY PRIOR EMPNO = MGR
ORDER SIBLINGS BY SAL DESC;