-- 094. 임시 테이블 생성하기

-- ON COMMIT DELETE ROWS: COMMIT 할 때까지만 데이터 보관
-- ON COMMIT PRESERVE ROWS: 현재 SESSION이 종료될 때까지만 데이터 보관
CREATE GLOBAL TEMPORARY TABLE EMP37
(EMPNO NUMBER(10),
 ENAME VARCHAR2(10),
 SAL NUMBER(10,2))
 ON COMMIT DELETE ROWS;
 