-- 096. 복잡한 쿼리를 단순하게 하기2

CREATE VIEW EMP_VIEW2 AS
    SELECT DEPTNO, ROUND(AVG(SAL)) AS 평균월급
    FROM EMP
    GROUP BY DEPTNO;


-- VIEW를 사용하면 다음과 같이 서브쿼리 대신 EMP_VIEW2로 간단하게 작성 가능
-- 서브쿼리 이용
SELECT K1.ENAME, K1.DEPTNO, K1.SAL, K2.평균월급
FROM EMP K1, (SELECT DEPTNO, ROUND(AVG(SAL)) AS 평균월급
              FROM EMP
              GROUP BY DEPTNO;) K2
WHERE K1.DEPTNO = K2.DEPTNO AND K1.SAL > K2.평균월급
-- VIEW 이용
SELECT K1.ENAME, K1.DEPTNO, K1.SAL, K2.평균월급
FROM EMP K1, EMP_VIEW2 K2
WHERE K1.DEPTNO = K2.DEPTNO AND K1.SAL > K2.평균월급