-- 104. 데이터의 품질 높이기

-- PRIMARY KEY: 중복 및 NULL 불가
-- CONSTRAINT 키워드 제약
CREATE TABLE DEPT2
(DEPTNO NUMBER(10) CONSTRAINT DEPT2_DEPTNO_PK PRIMARY KEY,
 DNAME VARCHAR2(14),
LOC VARCHAR2(10));

-- 테이블에 생성된 제약 확인
SELECT K1.CONSTRAINT_NAME AS 제약이름, K1.CONSTRAINT_TYPE AS 제약유형, K2.COLUMN_NAME AS 제약컬럼
FROM USER_CONSTRAINTS K1, USER_CONS_COLUMNS K2
WHERE K1.TABLE_NAME = 'DEPT2'
AND K1.CONSTRAINT_NAME = K2.CONSTRAINT_NAME;

-- 테이블 생성 이후 제약 추가
DROP TABLE DEPT2;

CREATE TABLE DEPT2
(DEPTNO NUMBER(10),
 DNAME VARCHAR2(14),
LOC VARCHAR2(10));

ALTER TABLE DEPT2
ADD CONSTRAINT DEPT2_DEPTNO_PK PRIMARY KEY(DEPTNO);