-- 106. 데이터의 품질 높이기3

-- NOT NULL: NULL값 입력 불가
CREATE TABLE DEPT5
(DEPTNO NUMBER(10),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(10) CONSTRAINT DEPT5_LOC_NN NOT NULL);

 -- 테이블에 생성된 제약 확인
SELECT K1.CONSTRAINT_NAME AS 제약이름, K1.CONSTRAINT_TYPE AS 제약유형, K2.COLUMN_NAME AS 제약컬럼
FROM USER_CONSTRAINTS K1, USER_CONS_COLUMNS K2
WHERE K1.TABLE_NAME = 'DEPT5'
AND K1.CONSTRAINT_NAME = K2.CONSTRAINT_NAME;

-- 테이블 생성 이후 제약 추가
-- MODIFY로 추가하며 기존에 NULL값이 없어야만 생성가능
DROP TABLE DEPT5;

CREATE TABLE DEPT5
(DEPTNO NUMBER(10),
 DNAME VARCHAR2(14),
LOC VARCHAR2(10));

ALTER TABLE DEPT5
MODIFY LOC CONSTRAINT DEPT5_LOC_NN NOT NULL;