-- 107. 데이터의 품질 높이기4

-- CHECK: 지정된 데이터만 입력가능
CREATE TABLE EMP6
(EMPNO NUMBER(10),
 ENAME VARCHAR2(14),
 SAL NUMBER(10) CONSTRAINT EMP6_SAL_CK CHECK(SAL BETWEEN 0 AND 6000) );

 -- 테이블에 생성된 제약 확인
SELECT K1.CONSTRAINT_NAME AS 제약이름, K1.CONSTRAINT_TYPE AS 제약유형, K2.COLUMN_NAME AS 제약컬럼
FROM USER_CONSTRAINTS K1, USER_CONS_COLUMNS K2
WHERE K1.TABLE_NAME = 'EMP6'
AND K1.CONSTRAINT_NAME = K2.CONSTRAINT_NAME;

-- 테이블 제약 제거
ALTER TABLE EMP6
DROP CONSTRAINT EMP6_SAL_CK;