-- 108. 데이터의 품질 높이기5

-- FOREIGN KEY: 다른 테이블의 데이터를 참조
-- 부모 테이블
CREATE TABLE DEPT7
(DEPTNO NUMBER(10) CONSTRAINT DEPT7_DEPTNO_PK PRIMARY KEY,
 DNAME VARCHAR2(14),
 LOC VARCHAR2(10));

-- 자식 테이블
CREATE TABLE EMP7
(EMPNO NUMBER(10),
 ENAME VARCHAR2(20),
 SAL NUMBER(10),
 DEPTNO NUMBER(10) CONSTRAINT EMP7_DEPTNO_FK REFERENCES DEPT7(DEPTNO));

 -- 테이블에 생성된 제약 확인
SELECT K1.CONSTRAINT_NAME AS 제약이름, K1.CONSTRAINT_TYPE AS 제약유형, K2.COLUMN_NAME AS 제약컬럼
FROM USER_CONSTRAINTS K1, USER_CONS_COLUMNS K2
WHERE K1.TABLE_NAME IN ('DEPT7', 'EMP7')
AND K1.CONSTRAINT_NAME = K2.CONSTRAINT_NAME;

-- 부모 테이블의 PRIMARY KEY 삭제를 위해선 CASCADE 옵션을 추가
-- 자식 테이블의 FOREIGN KEY도 같이 삭제 된다
ALTER TABLE DEPT7
DROP CONSTRAINT DEPT7_DEPTNO_PK CASCADE;