-- 011. 비교 연산자 배우기2
-- BETWEEN AND
SELECT ENAME, SAL
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 3000;

-- 동일 구문
SELECT ENAME, SAL
FROM EMP
WHERE (SAL > 1000 OR SAL < 3000);

-- 날짜에도 사용가능
-- 현재 날짜 FORMAT = DD/MON/RR
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '01/JAN/81' AND '31/DEC/81';