-- 015. 논리 연산자 배우기 (AND, OR, NOT)
SELECT ENAME, SAL, JOB
FROM EMP
WHERE JOB = 'SALESMAN' AND SAL >= 1200;

SELECT ENAME, SAL, JOB
FROM EMP
WHERE JOB = 'SALESMAN' OR SAL >= 1200;

SELECT ENAME, JOB
FROM EMP
WHERE JOB NOT IN ('SALESMAN', 'ANALYST') AND ENAME LIKE '%S';